### PR TITLE
Amend council link at top of homepage and page template

### PR DESCRIPTION
**Pull request by J-Coke**

### CODE REVIEW

**Comment by J-Coke** [comment]
Screenshot 2022-08-10 at 16 03 44
Screenshot 2022-08-10 at 16 04 51

**Comment by Joseaie** [comment]
Is this meant to be a link?

**Comment by J-Coke** [comment]
> 

Not sure, I copied it from another page! I think it makes sense to have it as a link though?

**Comment by Joseaie** [comment]
> > 
> 
> Not sure, I copied it from another page! I think it makes sense to have it as a link though?

Might be best confirm with UCD?

**Pull request merged**
